#!/bin/bash

MODELS=( "gcn" "fishergcn" "gcnT" "fishergcnT" )
SMALLDATA=( "cora" "citeseer" )
LARGEDATA=( "pubmed" "ms_academic_cs" "amazon_electronics_photo" "amazon_electronics_computers" )

EXEC="hpc/exec_grid.sh"

# these configurations are generated by 'submit_hyperopt.sh'
GCN_CONFIG="--lrate 0.01 --dropout 0.5 --weight_decay 0.0005 --hidden 64"
FISHER_CONFIG="$GCN_CONFIG --fisher_noise 0.2 --fisher_rank 50"

REPEAT_ARGS="--randomsplit 20 --repeat 10 --seed 2019"
REPEAT_H0="--randomsplit 5 --repeat 10 --seed 2019"
REPEAT_H1="--randomsplit 5 --repeat 10 --seed 2024"
REPEAT_H2="--randomsplit 5 --repeat 10 --seed 2029"
REPEAT_H3="--randomsplit 5 --repeat 10 --seed 2034"

for DATA in ${SMALLDATA[@]}; do
  sbatch --mem 8g ${EXEC} ${DATA} gcn        ${REPEAT_ARGS} ${GCN_CONFIG}
  sbatch --mem 8g ${EXEC} ${DATA} fishergcn  ${REPEAT_ARGS} ${FISHER_CONFIG}
  sbatch --mem 8g ${EXEC} ${DATA} gcnT       ${REPEAT_ARGS} ${GCN_CONFIG}
  sbatch --mem 8g ${EXEC} ${DATA} fishergcnT ${REPEAT_ARGS} ${FISHER_CONFIG}
done

for DATA in ${LARGEDATA[@]}; do
  sbatch --mem 48g ${EXEC} ${DATA} gcn        ${REPEAT_ARGS} ${GCN_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} fishergcn  ${REPEAT_ARGS} ${FISHER_CONFIG}

  sbatch --mem 48g ${EXEC} ${DATA} gcnT       ${REPEAT_H0} ${GCN_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} gcnT       ${REPEAT_H1} ${GCN_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} gcnT       ${REPEAT_H2} ${GCN_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} gcnT       ${REPEAT_H3} ${GCN_CONFIG}

  sbatch --mem 48g ${EXEC} ${DATA} fishergcnT ${REPEAT_H0} ${FISHER_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} fishergcnT ${REPEAT_H1} ${FISHER_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} fishergcnT ${REPEAT_H2} ${FISHER_CONFIG}
  sbatch --mem 48g ${EXEC} ${DATA} fishergcnT ${REPEAT_H3} ${FISHER_CONFIG}
done

echo you are all done
